### ISSUE TITLE
ValueError in terracotta server when connecting with terracotta connect

### ISSUE THREAD

**Issue by mrpgraae** [DHI-GRAS/terracotta#120]
The error seems to happen, weirdly enough, only when the frontend tries to fetch the magma colormap. All the other colormaps work fine.

Full server log ouput with traceback:

```
(terracotta) λ terracotta serve --debug -d tst.sqlite
 * Serving Flask app "terracotta.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.                                                                                   
   Use a production WSGI server instead.                                                                                                                     
 * Debug mode: on                                                                                                                                            
 * Restarting with stat                                                                                                                                      
 * Debugger is active!                                                                                                                                       
 * Debugger PIN: 134-049-503                                                                                                                                 
 * Running on http://localhost:5000/ (Press CTRL+C to quit)                                                                                                  
127.0.0.1 - - [11/Jan/2019 09:41:55] "GET /keys HTTP/1.1" 200 -                                                                                              
127.0.0.1 - - [11/Jan/2019 09:41:56] "GET /swagger.json HTTP/1.1" 200 -                                                                                      
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=greys_r&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                      
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=viridis&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                      
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=rdbu_r&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                       
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=bugn&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                         
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=ylgn&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                         
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=magma&stretch_range=[0,1]&num_values=100 HTTP/1.1" 500 -                                        
Traceback (most recent call last):                                                                                                                           
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 2309, in __call__                             
    return self.wsgi_app(environ, start_response)                                                                                                            
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 2295, in wsgi_app                             
    response = self.handle_exception(e)                                                                                                                      
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1741, in handle_exception                     
    reraise(exc_type, exc_value, tb)                                                                                                                         
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\_compat.py", line 35, in reraise                            
    raise value                                                                                                                                              
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 2292, in wsgi_app                             
    response = self.full_dispatch_request()                                                                                                                  
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request                
    rv = self.handle_user_exception(e)                                                                                                                       
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1718, in handle_user_exception                
    reraise(exc_type, exc_value, tb)                                                                                                                         
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\_compat.py", line 35, in reraise                            
    raise value                                                                                                                                              
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request                
    rv = self.dispatch_request()                                                                                                                             
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1799, in dispatch_request                     
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                               
  File "c:\users\phgr\documents\terracotta\terracotta\server\flask_api.py", line 50, in inner                                                                
    return fun(*args, **kwargs)                                                                                                                              
  File "c:\users\phgr\documents\terracotta\terracotta\server\colormap.py", line 79, in get_colormap                                                          
    payload = {'colormap': colormap(**options)}                                                                                                              
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\contextlib.py", line 52, in inner                                               
    return func(*args, **kwds)                                                                                                                               
  File "c:\users\phgr\documents\terracotta\terracotta\handlers\colormap.py", line 26, in colormap                                                            
    cmap = get_cmap(colormap)                                                                                                                                
  File "c:\users\phgr\documents\terracotta\terracotta\cmaps\__init__.py", line 39, in get_cmap                                                               
    cmap_data = np.load(f)                                                                                                                                   
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\numpy\lib\npyio.py", line 433, in load                            
    pickle_kwargs=pickle_kwargs)                                                                                                                             
  File "C:\Users\phgr\AppData\Local\Continuum\Miniconda2\envs\terracotta\lib\site-packages\numpy\lib\format.py", line 698, in read_array                     
    array.shape = shape                                                                                                                                      
ValueError: cannot reshape array of size 764 into shape (255,3)                                                                                              
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=gist_earth&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -                                   
127.0.0.1 - - [11/Jan/2019 09:41:59] "GET /colormap?colormap=ocean&stretch_range=[0,1]&num_values=100 HTTP/1.1" 200 -
```

**Comment by mrpgraae** [comment]
```ValueError: cannot reshape array of size 764 into shape (255,3)```
Seems to indicate that there is 1 value missing from the saved colormap for some reason, since 3*255 == 765 and not 764.

**Comment by dionhaefner** [comment]
No idea what's going on, definitely works for me. Some thoughts:

- Check the path it is trying to load, maybe there are old files in there that didn't get overwritten during upgrading for some reason
- Double-check that npy files are portable
