### ISSUE TITLE
Zappa Deployment Issue awscli/botocore

### ISSUE THREAD

**Issue by vlro** [DHI-GRAS/terracotta#130]
Zappa deployment fails with the error:
```console
Error: Warning! Status check on the deployed lambda failed. A GET request to '/keys' yielded a 500 response code.
```
`zappa tail` returns the following:

```console
Calling tail for stage development..
[1551959388082] [DEBUG] 2019-03-07T11:49:48.82Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Zappa Event: {'resource': '/{proxy+}', 'path': '/keys', 'httpMethod': 'GET', 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'CloudFront-Forwarded-Proto': 'https', 'CloudFront-Is-Desktop-Viewer': 'true', 'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer': 'false', 'CloudFront-Is-Tablet-Viewer': 'false', 'CloudFront-Viewer-Country': 'DK', 'Host': 'xqy0a2486k.execute-api.eu-central-1.amazonaws.com', 'User-Agent': 'python-requests/2.21.0', 'Via': '1.1 4dace287624efad347124feabb88c0bc.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'zW-HC5PO-iT359qDMM8w4-MGo4DqV7Xw5mOoa0eD1HkxFvLhYKymGg==', 'X-Amzn-Trace-Id': 'Root=1-5c810557-cd013c07ae0d4617e19e6902', 'X-Forwarded-For': '193.3.62.162, 52.46.41.13', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept': ['*/*'], 'Accept-Encoding': ['gzip, deflate'], 'CloudFront-Forwarded-Proto': ['https'], 'CloudFront-Is-Desktop-Viewer': ['true'], 'CloudFront-Is-Mobile-Viewer': ['false'], 'CloudFront-Is-SmartTV-Viewer': ['false'], 'CloudFront-Is-Tablet-Viewer': ['false'], 'CloudFront-Viewer-Country': ['DK'], 'Host': ['xqy0a2486k.execute-api.eu-central-1.amazonaws.com'], 'User-Agent': ['python-requests/2.21.0'], 'Via': ['1.1 4dace287624efad347124feabb88c0bc.cloudfront.net (CloudFront)'], 'X-Amz-Cf-Id': ['zW-HC5PO-iT359qDMM8w4-MGo4DqV7Xw5mOoa0eD1HkxFvLhYKymGg=='], 'X-Amzn-Trace-Id': ['Root=1-5c810557-cd013c07ae0d4617e19e6902'], 'X-Forwarded-For': ['193.3.62.162, 52.46.41.13'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': {'proxy': 'keys'}, 'stageVariables': None, 'requestContext': {'resourceId': 'd5bbpn', 'resourcePath': '/{proxy+}', 'httpMethod': 'GET', 'extendedRequestId': 'WK3FrGm2liAFg4g=', 'requestTime': '07/Mar/2019:11:49:43 +0000', 'path': '/development/keys', 'accountId': '535685957976', 'protocol': 'HTTP/1.1', 'stage': 'development', 'domainPrefix': 'xqy0a2486k', 'requestTimeEpoch': 1551959383528, 'requestId': '191d776d-40cf-11e9-ad5a-7510dfe83f74', 'identity': {'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId': None, 'caller': None, 'sourceIp': '193.3.62.162', 'accessKey': None, 'cognitoAuthenticationType': None, 'cognitoAuthenticationProvider': None, 'userArn': None, 'userAgent': 'python-requests/2.21.0', 'user': None}, 'domainName': 'xqy0a2486k.execute-api.eu-central-1.amazonaws.com', 'apiId': 'xqy0a2486k'}, 'body': None, 'isBase64Encoded': False}
[1551959388420] [DEBUG] 2019-03-07T11:49:48.407Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388420] [DEBUG] 2019-03-07T11:49:48.420Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable config_file from defaults.
[1551959388420] [DEBUG] 2019-03-07T11:49:48.420Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable credentials_file from defaults.
[1551959388420] [DEBUG] 2019-03-07T11:49:48.420Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable data_path from defaults.
[1551959388566] [DEBUG] 2019-03-07T11:49:48.566Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading JSON file: /var/runtime/boto3/data/s3/2006-03-01/resources-1.json
[1551959388567] [DEBUG] 2019-03-07T11:49:48.567Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable region from environment with value 'eu-central-1'.
[1551959388567] [DEBUG] 2019-03-07T11:49:48.567Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388567] [DEBUG] 2019-03-07T11:49:48.567Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable ca_bundle from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable credentials_file from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable config_file from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable metadata_service_timeout from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388568] [DEBUG] 2019-03-07T11:49:48.568Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable metadata_service_num_attempts from defaults.
[1551959388601] [DEBUG] 2019-03-07T11:49:48.600Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388601] [DEBUG] 2019-03-07T11:49:48.601Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Looking for credentials via: env
[1551959388601] [INFO] 2019-03-07T11:49:48.601Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Found credentials in environment variables.
[1551959388602] [DEBUG] 2019-03-07T11:49:48.602Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading JSON file: /var/runtime/botocore/data/endpoints.json
[1551959388607] [DEBUG] 2019-03-07T11:49:48.607Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading variable profile from defaults.
[1551959388607] [DEBUG] 2019-03-07T11:49:48.607Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f01be4e8488>
[1551959388629] [DEBUG] 2019-03-07T11:49:48.629Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Loading JSON file: /var/runtime/botocore/data/s3/2006-03-01/service-2.json
[1551959388645] [DEBUG] 2019-03-07T11:49:48.645Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f01be4b11e0>
[1551959388645] [DEBUG] 2019-03-07T11:49:48.645Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f01bd4e3ea0>
[1551959388727] [DEBUG] 2019-03-07T11:49:48.727Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 streaming subsegments...
[1551959388741] [DEBUG] 2019-03-07T11:49:48.741Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 sending: {"format":"json","version":1}
{"cause": {"exceptions": [{"id": "faa9a9b8a108983c", "message": "cannot import name 'ReadTimeoutError'", "remote": false, "stack": [{"label": "<module>", "line": 576, "path": "bootstrap.py"}, {"label": "main", "line": 571, "path": "bootstrap.py"}, {"label": "handle_event_request", "line": 250, "path": "bootstrap.py"}, {"label": "lambda_handler", "line": 580, "path": "handler.py"}, {"label": "lambda_handler", "line": 248, "path": "handler.py"}, {"label": "handler", "line": 518, "path": "handler.py"}, {"label": "from_app", "line": 939, "path": "wrappers.py"}, {"label": "_run_wsgi_app", "line": 59, "path": "wrappers.py"}, {"label": "run_wsgi_app", "line": 923, "path": "test.py"}, {"label": "__call__", "line": 70, "path": "middleware.py"}, {"label": "__call__", "line": 2309, "path": "app.py"}, {"label": "wsgi_app", "line": 2292, "path": "app.py"}, {"label": "full_dispatch_request", "line": 1813, "path": "app.py"}, {"label": "dispatch_request", "line": 1799, "path": "app.py"}, {"label": "inner", "line": 50, "path": "flask_api.py"}, {"label": "get_keys", "line": 39, "path": "keys.py"}, {"label": "inner", "line": 52, "path": "contextlib.py"}, {"label": "keys", "line": 19, "path": "keys.py"}, {"label": "inner", "line": 19, "path": "base.py"}, {"label": "__enter__", "line": 81, "path": "contextlib.py"}, {"label": "_connect", "line": 124, "path": "sqlite.py"}, {"label": "_connection_callback", "line": 118, "path": "sqlite_remote.py"}, {"label": "wrapper", "line": 87, "path": "__init__.py"}, {"label": "inner", "line": 52, "path": "contextlib.py"}, {"label": "inner", "line": 52, "path": "contextlib.py"}, {"label": "__exit__", "line": 99, "path": "contextlib.py"}, {"label": "trace", "line": 23, "path": "profile.py"}], "type": "ImportError"}], "working_directory": "/var/task"}, "end_time": 1551959388.7275693, "fault": true, "id": "ce1c7178ee72bedd", "in_progress": false, "name": "download_db_from_s3", "namespace": "local", "parent_id": "118e5337bf93bec1", "start_time": 1551959388.4041536, "trace_id": "1-5c810557-cd013c07ae0d4617e19e6902", "type": "subsegment"} to 169.254.79.2:2000.
[1551959388741] [DEBUG] 2019-03-07T11:49:48.741Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 streaming subsegments...
[1551959388742] [DEBUG] 2019-03-07T11:49:48.741Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 sending: {"format":"json","version":1}
{"cause": "faa9a9b8a108983c", "end_time": 1551959388.7415833, "fault": true, "id": "118e5337bf93bec1", "in_progress": false, "name": "keys_handler", "namespace": "local", "parent_id": "67cebf4a0ab530f4", "start_time": 1551959388.3068833, "trace_id": "1-5c810557-cd013c07ae0d4617e19e6902", "type": "subsegment"} to 169.254.79.2:2000.
[1551959388753] [ERROR] 2019-03-07T11:49:48.742Z 729b7fbd-7b0d-4221-87d9-b52a712f0122 Exception on /keys [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2292, in wsgi_app
  response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1815, in full_dispatch_request
  rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1718, in handle_user_exception
  reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 35, in reraise
  raise value
  File "/var/task/flask/app.py", line 1813, in full_dispatch_request
  rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1799, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/task/terracotta/server/flask_api.py", line 50, in inner
  return fun(*args, **kwargs)
  File "/var/task/terracotta/server/keys.py", line 39, in get_keys
  payload = {'keys': keys()}
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/task/terracotta/handlers/keys.py", line 19, in keys
  for key, description in driver.get_keys().items():
  File "/var/task/terracotta/drivers/base.py", line 19, in inner
  with self.connect():
  File "/var/lang/lib/python3.6/contextlib.py", line 81, in __enter__
  return next(self.gen)
  File "/var/task/terracotta/drivers/sqlite.py", line 124, in _connect
  self._connection_callback()
  File "/var/task/terracotta/drivers/sqlite_remote.py", line 118, in _connection_callback
  self._update_db(self._remote_path, self.path)
  File "/var/task/cachetools/__init__.py", line 87, in wrapper
  v = method(self, *args, **kwargs)
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/task/terracotta/drivers/sqlite_remote.py", line 115, in _update_db
  _update_from_s3(remote_path, local_path)
  File "/var/task/terracotta/drivers/sqlite_remote.py", line 45, in _update_from_s3
  s3 = boto3.resource('s3')
  File "/var/runtime/boto3/__init__.py", line 100, in resource
  return _get_default_session().resource(*args, **kwargs)
  File "/var/runtime/boto3/session.py", line 389, in resource
  aws_session_token=aws_session_token, config=config)
  File "/var/runtime/boto3/session.py", line 263, in client
  aws_session_token=aws_session_token, config=config)
  File "/var/runtime/botocore/session.py", line 885, in create_client
  client_config=config, api_version=api_version)
  File "/var/runtime/botocore/client.py", line 70, in create_client
  cls = self._create_client_class(service_name, service_model)
  File "/var/runtime/botocore/client.py", line 95, in _create_client_class
  base_classes=bases)
  File "/var/runtime/botocore/hooks.py", line 227, in emit
  return self._emit(event_name, kwargs)
  File "/var/runtime/botocore/hooks.py", line 210, in _emit
  response = handler(**kwargs)
  File "/var/runtime/boto3/utils.py", line 61, in _handler
  module = import_module(module)
  File "/var/runtime/boto3/utils.py", line 52, in import_module
  __import__(name)
  File "/var/runtime/boto3/s3/inject.py", line 15, in <module>
  from boto3.s3.transfer import create_transfer_manager
  File "/var/runtime/boto3/s3/transfer.py", line 129, in <module>
  from s3transfer.manager import TransferConfig as S3TransferConfig
  File "/var/task/s3transfer/manager.py", line 21, in <module>
  from s3transfer.utils import get_callbacks
  File "/var/task/s3transfer/utils.py", line 27, in <module>
  from botocore.exceptions import ReadTimeoutError
ImportError: cannot import name 'ReadTimeoutError'
```
This is what the environment looks like:
```
affine==2.2.2
apispec==1.0.0
apispec-webframeworks==0.3.0
argcomplete==1.9.3
attrs==19.1.0
aws-xray-sdk==2.4.2
awscli==1.16.119
boto3==1.9.109
botocore==1.12.109
cachetools==3.1.0
certifi==2018.11.29
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
colorama==0.3.9
docutils==0.14
durationpy==0.5
Flask==1.0.2
Flask-Cors==3.0.7
future==0.17.1
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.4
jsonpickle==1.1
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
marshmallow==3.0.0rc4
mercantile==1.0.4
numpy==1.16.2
Pillow==5.4.1
placebo==0.9.0
pyasn1==0.4.5
pyparsing==2.3.1
python-dateutil==2.8.0
python-slugify==1.2.4
PyYAML==3.13
rasterio==1.0.21
requests==2.21.0
rsa==3.4.2
s3transfer==0.2.0
Shapely==1.6.4.post2
six==1.12.0
snuggs==1.4.3
-e git+https://github.com/DHI-GRAS/terracotta.git@cc3774bb52d7c9db9c6fd772f39af8fb5e8f96fa#egg=terracotta
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.5
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.11.1
wsgi-request-logger==0.4.6
zappa==0.47.1
```

When awscli, boto3, botocore, s3 transfer are downgraded the deployment works. The environment for a **working** deployment looks like:

```
affine==2.2.2
apispec==1.0.0
apispec-webframeworks==0.3.0
argcomplete==1.9.3
attrs==19.1.0
aws-xray-sdk==2.4.2
awscli==1.16.85
boto3==1.9.75
botocore==1.12.75
cachetools==3.1.0
certifi==2018.11.29
cfn-flip==1.1.0.post1
chardet==3.0.4
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
colorama==0.3.9
docutils==0.14
durationpy==0.5
Flask==1.0.2
Flask-Cors==3.0.7
future==0.17.1
hjson==3.0.1
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
jmespath==0.9.4
jsonpickle==1.1
kappa==0.6.0
lambda-packages==0.20.0
MarkupSafe==1.1.1
marshmallow==3.0.0rc4
mercantile==1.0.4
numpy==1.16.2
Pillow==5.4.1
placebo==0.9.0
pyasn1==0.4.5
pyparsing==2.3.1
python-dateutil==2.8.0
python-slugify==1.2.4
PyYAML==3.13
rasterio==1.0.21
requests==2.21.0
rsa==3.4.2
s3transfer==0.1.13
Shapely==1.6.4.post2
six==1.12.0
snuggs==1.4.3
-e git+https://github.com/DHI-GRAS/terracotta.git@cc3774bb52d7c9db9c6fd772f39af8fb5e8f96fa#egg=terracotta
toml==0.10.0
tqdm==4.19.1
troposphere==2.4.5
Unidecode==1.0.23
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.11.1
wsgi-request-logger==0.4.6
zappa==0.47.1
```

**Comment by dionhaefner** [comment]
That's odd. The boto toolchain is preinstalled on Lambda, so it should be excluded during deployment: 

https://github.com/DHI-GRAS/terracotta/blob/26ef2f61bd8306fd8fecd27288df6426a6751534/zappa_settings.toml.in#L8-L17

Apparently this doesn't work for some reason. Maybe `s3transfer` needs to be excluded, too - it's the first time I hear of this package.

**Comment by vlro** [comment]
Yup, that did it. I added "s3transfer*" to the exclude list and deployment worked fine. Thanks @dionhaefner 

Aside from this, perhaps it could also be worth pinning `future`, `jmespath` and `python-dateutil` in zappa_requirements to avoid this warning:

``
zappa 0.47.1 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.
zappa 0.47.1 has requirement jmespath==0.9.3, but you'll have jmespath 0.9.4 which is incompatible.
zappa 0.47.1 has requirement python-dateutil<2.7.0,>=2.6.1, but you'll have python-dateutil 2.8.0 which is incompatible.
```

Could also consider adding awscli to zappa_requirements since that's used for deployment as well.

**Comment by j08lue** [comment]
Yes, the problem here is that a recent `s3transfer` depends on a newer version of `botocore`. If you only push one of them to Lambda, the versions are not compatible. @vlro and I were fighting with that, too, yesterday.
