### ISSUE TITLE
DistributionNotFound error

### ISSUE THREAD

**Issue by panakouris** [DHI-GRAS/terracotta#131]
In linux, after creating a conda environment and installing terracotta succesfully, I get the following error:

```
terracotta optimize-rasters --help
Traceback (most recent call last):
  File "/home/pako/.conda/envs/terracotta/bin/terracotta", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/pako/.conda/envs/terracotta/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyYAML>=3.10; extra == "yaml"' distribution was not found and is required by apispec
```
After installing PyYAML it works fine.
The error comes with either Python 3.6 or 3.7

**Comment by dionhaefner** [comment]
How did you set up the environment? Via the environment file or manually?

**Comment by panakouris** [comment]
Via the environment file

**Comment by dionhaefner** [comment]
Guess that's a missing dependency in some conda recipe then.
