### ISSUE TITLE
ModuleNotFoundError: No module named 'apispec.ext.flask'

### ISSUE THREAD

**Issue by jankovicgd** [DHI-GRAS/terracotta#132]
I have an modules issue running terracotta. I have tried installing with pip and setuptools. Running `terracotta serve -r` which causes following stack trace:

```
 [-] Uncaught exception!
Traceback (most recent call last):
  File "/home/ubuntu/terracotta/terracotta/terracotta/scripts/cli.py", line 52, in entrypoint
    cli(obj={})
  File "/home/ubuntu/.virtualenvs/terracotta/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/terracotta/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.virtualenvs/terracotta/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.virtualenvs/terracotta/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.virtualenvs/terracotta/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/terracotta/terracotta/terracotta/scripts/serve.py", line 57, in serve
    from terracotta.server import create_app
  File "/home/ubuntu/terracotta/terracotta/terracotta/server/__init__.py", line 6, in <module>
    from terracotta.server.flask_api import create_app  # noqa: F401
  File "/home/ubuntu/terracotta/terracotta/terracotta/server/flask_api.py", line 5, in <module>
    import apispec.ext.flask
ModuleNotFoundError: No module named 'apispec.ext.flask'
```

Output of `pip freeze`:
```
affine==2.2.2
apispec==1.1.0
attrs==19.1.0
cachetools==3.1.0
Click==7.0
click-plugins==1.0.4
cligj==0.5.0
Flask==1.0.2
Flask-Cors==3.0.7
itsdangerous==1.1.0
Jinja2==2.10
MarkupSafe==1.1.1
marshmallow==3.0.0rc4
mercantile==1.0.4
numpy==1.16.2
Pillow==5.4.1
pkg-resources==0.0.0
pyparsing==2.3.1
rasterio==1.0.22
Shapely==1.7a1
six==1.12.0
snuggs==1.4.3
-e git+https://github.com/DHI-GRAS/terracotta.git@0591d803e1e4d3eadc55b75657b7293bf188bf0e#egg=terracotta
toml==0.10.0
tqdm==4.31.1
Werkzeug==0.15.1
```

Version: 0.5.0
Running on: Ubuntu 16.04.5 LTS

**Comment by dionhaefner** [comment]
This should be fixed in current master. Alternatively you can downgrade to `apispec<1.0`.

**Comment by jankovicgd** [comment]
Indeed it works. Thanks for the fast reply :)

**Comment by dionhaefner** [comment]
Happy to help! Let us know if you run into anything else.
