### ISSUE TITLE
Problems with new tile cache compression

### ISSUE THREAD

**Issue by mrpgraae** [DHI-GRAS/terracotta#136]
I tried using tc to do some data exploration, by doing `terracotta serve -r {}_{some}_{key}.tif` and then `terracotta connect localhost:5000` as described in the docs. Whenever the app requests a tile, I see this stack trace in the server:
```
Traceback (most recent call last):
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\server\flask_api.py", line 50, in inner
    return fun(*args, **kwargs)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\server\singleband.py", line 121, in get_singleband
    return _get_singleband_image(keys, tile_xyz)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\server\singleband.py", line 166, in _get_singleband_image
    image = singleband(parsed_keys, tile_xyz=tile_xyz, **options)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\handlers\singleband.py", line 45, in singleband
    tile_size=tile_size, preserve_values=preserve_values
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\xyz.py", line 46, in get_tile_data
    preserve_values=preserve_values, asynchronous=asynchronous
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\drivers\base.py", line 20, in inner
    return fun(self, *args, **kwargs)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\drivers\raster_base.py", line 610, in get_raster_tile
    return task()
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\cachetools\__init__.py", line 84, in wrapper
    return c[k]
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\drivers\raster_base.py", line 51, in __getitem__
    compressed_item = super().__getitem__(key)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\cachetools\lfu.py", line 16, in __getitem__
    value = cache_getitem(self, key)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\cachetools\cache.py", line 44, in __getitem__
    return self.__missing__(key)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\cachetools\cache.py", line 73, in __missing__
    self.__setitem__(key, value)
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\drivers\raster_base.py", line 55, in __setitem__
    super().__setitem__(key, self._compress_ma(value))
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\terracotta\drivers\raster_base.py", line 59, in _compress_ma
    compressed_data = zlib.compress(arr.data, self.compression_level)
AttributeError: 'int' object has no attribute 'data'
127.0.0.1 - - [03/Apr/2019 11:22:36] "GET /singleband/20171208/new/10/311/558.png?colormap=greys_r&stretch_range=[0.0025056349113583565,1.8937201499938965] HTTP/1.1" 500 - [2019-04-03 11:22:36,088] ERROR in app: Exception on /singleband/20171208/new/10/316/558.png [GET]
```

**Comment by mrpgraae** [comment]
I also see this one right after:
```
127.0.0.1 - - [03/Apr/2019 11:22:36] "GET /singleband/20171208/new/10/316/558.png?colormap=greys_r&stretch_range=[0.0025056349113583565,1.8937201499938965] HTTP/1.1" 500 - [2019-04-03 11:22:36,114] ERROR in app: Exception on /singleband/20171208/new/10/313/554.png [GET]
Traceback (most recent call last):
  File "c:\users\phgr\appdata\local\continuum\miniconda2\envs\terracotta\lib\site-packages\cachetools\cache.py", line 42, in __getitem__
    return self.__data[key]
KeyError: (SQLiteDriver('C:\Users\phgr\AppData\Local\Temp\tmpgqaetcyp.sqlite'), 'C:\\Test_data\\check-titicaca\\TB.2_chl_NTC_20171208_new.tif', <object object at 0x0000026338CCBC70>, 'bounds', (-7788015.937920038, -1682837.6147264398, -7748880.179438028, -1643701.8562444304), 'downsampling_method', 'nearest', 'preserve_values', False, 'tile_size', (256, 256), 'upsampling_method', 'cubic')
```

**Comment by mrpgraae** [comment]
@panakouris could not reproduce and advised to update cachetools, which worked, so this is fixed by a version constraint. Closing.

**Comment by dionhaefner** [comment]
... could you please add the version constraint, then? :)

**Comment by panakouris** [comment]
I added the version constraint
