### ISSUE TITLE
Error in running with latest versions marshmallow

### ISSUE THREAD

**Issue by bbb1991** [DHI-GRAS/terracotta#144]
Hello! 
When I trying to run with latest version marshmallow (that installs by default, when executing command `pip install terracotta`), command fails with exception:
```
(venv) ➜  test terracotta optimize-rasters 2000.tiff -o optimized
Traceback (most recent call last):
  File "/tmp/test/venv/bin/terracotta", line 6, in <module>
    from terracotta.scripts.cli import entrypoint
  File "/tmp/test/venv/lib/python3.7/site-packages/terracotta/__init__.py", line 21, in <module>
    _settings: TerracottaSettings = parse_config()
  File "/tmp/test/venv/lib/python3.7/site-packages/terracotta/config.py", line 141, in parse_config
    new_settings = schema.load(config_dict)
  File "/tmp/test/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 701, in load
    postprocess=True,
  File "/tmp/test/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 803, in _do_load
    partial=partial,
  File "/tmp/test/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1030, in _invoke_load_processors
    partial=partial,
  File "/tmp/test/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1156, in _invoke_processors
    data = processor(data, many=many, **kwargs)
TypeError: decode_lists() got an unexpected keyword argument 'many'
```

```
(venv) ➜  test pip freeze
affine==2.2.2
apispec==1.3.3
apispec-webframeworks==0.4.0
attrs==19.1.0
cachetools==3.1.1
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
Flask==1.0.3
Flask-Cors==3.0.8
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
marshmallow==3.0.0rc7
mercantile==1.0.4
numpy==1.16.4
Pillow==6.0.0
pyparsing==2.4.0
PyYAML==5.1.1
rasterio==1.0.24
Shapely==1.6.4.post2
six==1.12.0
snuggs==1.4.6
terracotta==0.5.1
toml==0.10.0
tqdm==4.32.1
Werkzeug==0.15.4
```
Downgrading marshmallow to `3.0.0b12` solves this problem. Maybe works with higher vesrsions, but not tested it.

**Comment by dionhaefner** [comment]
Thank you for the detailed bug report. Confirmed, working on a fix.

**Comment by dionhaefner** [comment]
Should be fixed now, please report back if you run into any other problems.

**Comment by danielgormly** [comment]
Hi I’m also receiving this issue (fresh install of Python 3.7, installed Terracotta using Pip)

**Comment by dionhaefner** [comment]
The version on PyPI is not updated yet. In the meantime, you can install the current master of Terracotta (`pip install git+https://github.com/DHI-GRAS/terracotta.git`), or downgrade marshmallow (`pip install "marshmallow==3.0.0b12"`).
