### ISSUE TITLE
MySQL driver issue - first Cursor closed then InterfaceError

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/terracotta#173]
I have recently used the MySQL driver a lot but never seen this error. 

Now I just inserted a lot of new data. `/datasets` worked fine at first, showing all the new entries. But then all the sudden not anymore:

```
Exception on /datasets [GET]
                                                                                                            
Traceback (most recent call last):
  File "/var/task/terracotta/drivers/mysql.py", line 42, in convert_exceptions
  yield
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/task/terracotta/drivers/mysql.py", line 334, in get_datasets
  list(where.values())
  File "/var/task/pymysql/cursors.py", line 165, in execute
  while self.nextset():
  File "/var/task/pymysql/cursors.py", line 107, in nextset
  return self._nextset(False)
  File "/var/task/pymysql/cursors.py", line 91, in _nextset
  conn = self._get_db()
  File "/var/task/pymysql/cursors.py", line 73, in _get_db
  raise err.ProgrammingError("Cursor closed")
pymysql.err.ProgrammingError: Cursor closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/task/terracotta/drivers/mysql.py", line 212, in _connect
  yield
  File "/var/task/terracotta/drivers/base.py", line 20, in inner
  return fun(self, *args, **kwargs)
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/lang/lib/python3.6/contextlib.py", line 99, in __exit__
  self.gen.throw(type, value, traceback)
  File "/var/task/terracotta/drivers/mysql.py", line 44, in convert_exceptions
  raise exceptions.InvalidDatabaseError(msg) from exc
terracotta.exceptions.InvalidDatabaseError: Could not retrieve datasets

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/terracotta/drivers/mysql.py", line 212, in _connect
  yield
  File "/var/task/terracotta/handlers/datasets.py", line 22, in datasets
  where=some_keys, page=page, limit=limit
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/task/terracotta/drivers/base.py", line 20, in inner
  return fun(self, *args, **kwargs)
  File "/var/lang/lib/python3.6/contextlib.py", line 99, in __exit__
  self.gen.throw(type, value, traceback)
  File "/var/task/terracotta/drivers/mysql.py", line 214, in _connect
  self._connection.rollback()
  File "/var/task/pymysql/connections.py", line 429, in rollback
  self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/var/task/pymysql/connections.py", line 750, in _execute_command
  raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2446, in wsgi_app
  response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1951, in full_dispatch_request
  rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1820, in handle_user_exception
  reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 39, in reraise
  raise value
  File "/var/task/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/task/terracotta/server/flask_api.py", line 49, in inner
  return fun(*args, **kwargs)
  File "/var/task/terracotta/server/datasets.py", line 78, in get_datasets
  'datasets': datasets(keys, page=page, limit=limit)
  File "/var/lang/lib/python3.6/contextlib.py", line 52, in inner
  return func(*args, **kwds)
  File "/var/task/terracotta/handlers/datasets.py", line 24, in datasets
  key_names = driver.key_names
  File "/var/lang/lib/python3.6/contextlib.py", line 99, in __exit__
  self.gen.throw(type, value, traceback)
  File "/var/task/terracotta/drivers/mysql.py", line 214, in _connect
  self._connection.rollback()
  File "/var/task/pymysql/connections.py", line 429, in rollback                                                                                                                                                                               self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/var/task/pymysql/connections.py", line 750, in _execute_command
  raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
```

**Comment by dionhaefner** [comment]
It looks like the connection goes stale for some reason, and the driver fails to re-open a new one. A possible cause could be this:

https://github.com/DHI-GRAS/terracotta/blob/5ceb6ad217d6eae705b3bc6e1358aeb3f565e38c/terracotta/drivers/mysql.py#L217-L222

If any of the first 3 lines fails, `self._connected` will stay `True`, and the driver won't try to open a new one despite it being broken.

You can try to wrap this into another `try: ... finally:` to ensure that `self._connected` is set to `False` even if the previous lines don't succeed, and see if that fixes the issue.

**Comment by j08lue** [comment]
Just thought the stale connection could have been due to automated RDS db maintenance. But that has a different time window.

The issue was gone when we checked again after about 12 hours.

But I'll implement the change you suggested to handle these errors better.

**Comment by dionhaefner** [comment]
... or just move `self._connected = False` to the top of this block :)
