### ISSUE TITLE
Error: VRT already has an alpha band

### ISSUE THREAD

**Issue by laxnpander** [DHI-GRAS/terracotta#176]
Hey there people,
I created some custom .tif file and would like to serve it with terracotta. However, I get the following error when calling
`terracotta serve -r {name}.tif`

Error message:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/terracotta/server/flask_api.py", line 49, in inner
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/terracotta/server/singleband.py", line 152, in get_singleband_preview
    return _get_singleband_image(keys)
  File "/usr/local/lib/python3.6/dist-packages/terracotta/server/singleband.py", line 166, in _get_singleband_image
    image = singleband(parsed_keys, tile_xyz=tile_xyz, **options)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/terracotta/handlers/singleband.py", line 45, in singleband
    tile_size=tile_size, preserve_values=preserve_values
  File "/usr/local/lib/python3.6/dist-packages/terracotta/xyz.py", line 27, in get_tile_data
    asynchronous=asynchronous
  File "/usr/local/lib/python3.6/dist-packages/terracotta/drivers/base.py", line 20, in inner
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/terracotta/drivers/raster_base.py", line 562, in get_raster_tile
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
rasterio.errors.WarpOptionsError: The VRT already has an alpha band, adding a new one is not supported`

My .tif file:
https://cloudstorage.tu-braunschweig.de/getlink/fiHGTTUZHaDHMjf9tiKBjvLC/ortho.tif

I guess the problem is the creation of my .tif file, probably some bad flags or channels? The map is not displayed in the preview tool. I see the outlines, but not more.

Thanks for your help and best regards,
Alex

**Comment by dionhaefner** [comment]
Thank you for the bug report. What version of rasterio is this?

**Comment by laxnpander** [comment]
@dionhaefner: `rasterio.__gdal_version__ ` gives me 2.4.4.

I just realized after following the workflow in the readme (optimize raster files, pack as sqlite db) it is displayed, but in greyscale.

**Comment by dionhaefner** [comment]
I can reproduce the error, so I'll see if I can find what's going on.

This raster is not cloud-optimized, so even if it would work, performance would be horrible. So you should do `terracotta optimize-rasters` regardless of this problem. Terracotta only supports single-band GTiffs, so to display it in RGB you will have to split the bands int separate files.

**Comment by laxnpander** [comment]
@dionhaefner: Alright, didn't know that. Thanks for the quick response! I tested a couple of open source tileserver over the past few days and Terracotta is my favourite so far. Really nice work!

**Comment by dionhaefner** [comment]
Should be fixed on master. Would be nice if you could verify. As I said, reading will be slow, so be patient :)

**Comment by laxnpander** [comment]
@dionhaefner: Hmm, how patient do I have to be? :D Currently hitting the 15 min but it seems to be still loading. On the pro side: I didn't get the error anymore!

**Comment by dionhaefner** [comment]
Should be fixed then. Feel free to report if you run into further problems.
