### ISSUE TITLE
Error when trying to serve raster of float datatype

### ISSUE THREAD

**Issue by abhi1301** [DHI-GRAS/terracotta#179]
```
127.0.0.1 - - [13/Jul/2020 00:31:22] "GET /singleband/4918/yield/0101201831012018/preview.png?tile_size=[128,128] HTTP/1.1" 500 -
 [-] Exception on /singleband/4918/yield/0101201831012018/preview.png [GET]
Traceback (most recent call last):
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/abhishek/Project/terracotta/terracotta/server/flask_api.py", line 49, in inner
    return fun(*args, **kwargs)
  File "/home/abhishek/Project/terracotta/terracotta/server/singleband.py", line 152, in get_singleband_preview
    return _get_singleband_image(keys)
  File "/home/abhishek/Project/terracotta/terracotta/server/singleband.py", line 166, in _get_singleband_image
    image = singleband(parsed_keys, tile_xyz=tile_xyz, **options)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/abhishek/Project/terracotta/terracotta/handlers/singleband.py", line 67, in singleband
    out = image.to_uint8(tile_data, *stretch_range_)
  File "/home/abhishek/Project/terracotta/terracotta/image.py", line 148, in to_uint8
    rescaled = contrast_stretch(data, (lower_bound, upper_bound), (1, 255), clip=True)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/abhishek/Project/terracotta/terracotta/image.py", line 134, in contrast_stretch
    out_data -= lower_bound_in
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/numpy/ma/core.py", line 4227, in __isub__
    self._data.__isub__(np.where(self._mask, self.dtype.type(0),
TypeError: ufunc 'subtract' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''
```

**Comment by dionhaefner** [comment]
Thank you for raising this. Unfortunately, I can't reproduce. Can you share your raster and which version of Terracotta, NumPy, and rasterio you are using?

**Comment by abhi1301** [comment]
I'm using the following versions:
- terracotta : version 0.6.1.dev6+gd467a30
- rasterio :  1.1.5
- numpy : 1.18.1
- GDAL  : 2.3.3
- rio-cogeo : 2.0a2

Using rio-cogeo to create valid COG files, with overviews and internal tiling.
There's also the following error when trying _**terracotta optimize-rasters**_ on float datatype rasters:
`Optimizing rasters:   0%|                          | [00:00<?, file=geoTiff.tif]
 [-] Uncaught exception!                                                        
Traceback (most recent call last):
  File "/home/abhishek/CropIn/terracotta/terracotta/scripts/cli.py", line 52, in entrypoint
    cli(obj={})
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abhishek/anaconda3/envs/gis_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/abhishek/CropIn/terracotta/terracotta/scripts/optimize_rasters.py", line 255, in optimize_rasters
    max_overview_level = math.ceil(math.log2(max(
ValueError: math domain error
`

I've attached the following zip containing my input raster files. It contains 2 files:
1. geoTiff.tif        :  My input file (float32 datatype), fails to be optimized by **_terracotta_**
2. coggeoTiff.tif  : COG version of the input file, created by rio-cogeo. Since terracotta failed to optimise the 'geoTiff.tif, I used rio-cogeo to create valid COG files and serve up via terracotta ( This method works perfectly fine with **_Byte_** or **_Int_** datatype rasters, but not for **_Float_**).

[geotiff.zip](https://github.com/DHI-GRAS/terracotta/files/4913422/geotiff.zip)

**Comment by dionhaefner** [comment]
Thanks! I can reproduce the problem now, and it seems like we're going to get at least 2 bugs fixed here. Working on it.

**Comment by dionhaefner** [comment]
`optimize-rasters` should work now, next up is an issue with how NaNs are handled internally.

**Comment by dionhaefner** [comment]
<img width="981" alt="Screen Shot 2020-07-14 at 12 09 17" src="https://user-images.githubusercontent.com/11994217/87413657-dffa2600-c5ca-11ea-9294-dc4e1579fb46.png">

Done. Feel free to reopen of the problem persists.

**Comment by abhi1301** [comment]
It seems the second issue with **_terracotta optimize-rasters_** was only with small size rasters as you said, I just verified, it's working for my large rasters. But just to be on same page, the first issue with serving the float datatype raster (terracotta optimized) is irrespective of the size, right?

**Comment by dionhaefner** [comment]
Yes, there were two problems:
1. `optimize-rasters` did not work on rasters smaller than `(256, 256)`.
2. Rasters containing a nodata value *and* NaN values could not be served. So, in general, float rasters *did* work, just not ones that also contain NaNs.
