### ISSUE TITLE
Cannot add custom colormap: v0.7.1

### ISSUE THREAD

**Issue by htejwani** [DHI-GRAS/terracotta#217]
I have added the env variable TC_EXTRA_CMAP_FOLDER to point to a folder containing my .npy file. However when I start the server with this command: `terracotta serve -r /home/.../{name}.tif --port 8000 --allow-all-ips` , I get the following error:

 ```
[-] Uncaught exception!
Traceback (most recent call last):
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/scripts/cli.py", line 52, in entrypoint
    cli(obj={})
  File "/home/SVaid/miniconda3/envs/terracotta/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/SVaid/miniconda3/envs/terracotta/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/SVaid/miniconda3/envs/terracotta/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/SVaid/miniconda3/envs/terracotta/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/SVaid/miniconda3/envs/terracotta/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/scripts/serve.py", line 104, in serve
    server_app = create_app(debug=debug, profile=profile)
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/server/flask_api.py", line 78, in create_app
    import terracotta.server.colormap
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/server/colormap.py", line 13, in <module>
    from terracotta.cmaps import AVAILABLE_CMAPS
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/cmaps/__init__.py", line 6, in <module>
    from terracotta.cmaps.get_cmaps import AVAILABLE_CMAPS, get_cmap  # noqa: F401
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/cmaps/get_cmaps.py", line 56, in <module>
    CMAP_FILES = _get_cmap_files()
  File "/home/SVaid/workspace/terracotta/terracotta/terracotta/cmaps/get_cmaps.py", line 46, in _get_cmap_files
    _read_cmap(f_path)
NameError: name '_read_cmap' is not defined
```

**Comment by dionhaefner** [comment]
Could you please try again with the current master?

**Comment by htejwani** [comment]
Working now, thankyou.
