### ISSUE TITLE
terracotta core dump with proj-data from ubuntugis

### ISSUE THREAD

**Issue by solsticedhiver** [DHI-GRAS/terracotta#239]
Hello,
I don't know where to report this and I don't know either what is causing this.

On ubuntu 20.04, with the ppa from terracotta core dump with proj-data from ubunutgis. I have email the admiin team of the repo. This is a copy.

I am trying to install terracotta (https://github.com/DHI-GRAS/terracotta/) in a python virtualenv and this leads to error and core dump when proj-data from ubuntuGIS repo is installed.

What I am doing is:

```
$ python3.9 -m venv tc4m
$ cd tc4m
$ source bin/activate
$ pip install terracotta
$ pip install Cython
$ pip install crick

$ terracotta
Usage: terracotta [OPTIONS] COMMAND [ARGS]...

  The command line interface for the Terracotta tile server.

  All flags must be passed before specifying a subcommand.

  Example:

      $ terracotta -c config.toml connect localhost:5000

Options:
  -c, --config TOML-FILE          Update global settings from this TOML file.
  --loglevel [debug|info|warning|error|critical]
                                  Set level for log messages
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  connect           Connect to a running Terracotta instance and interactively
                    explore data in it.

  ingest            Ingest a collection of raster files into a SQLite
                    database.

  optimize-rasters  Optimize a collection of raster files for use with
                    Terracotta.

  serve             Serve rasters through a local Flask development server.
free(): invalid pointer
Aborted (core dumped)

$ strace terracotta
[...]
fstat(4, {st_mode=S_IFREG|0664, st_size=1356, ...}) = 0
ioctl(4, TCGETS, 0x7fff96895090)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(4, 0, SEEK_CUR)                   = 0
lseek(4, 0, SEEK_CUR)                   = 0
fstat(4, {st_mode=S_IFREG|0664, st_size=1356, ...}) = 0
read(4, "a\r\r\n\0\0\0\0T\254\250a\255\4\0\0\343\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1357) = 1356
read(4, "", 1)                          = 0
close(4)                                = 0
ioctl(1, TCGETS, 0x7fff96896280)        = -1 ENOTTY (Inappropriate ioctl for device)
write(1, "Usage: terracotta [OPTIONS] COMM"..., 971) = 971
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f2914b3d3c0}, {sa_handler=0x55adcaa9b2f2, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f2914b3d3c0}, 8) = 0
stat("/usr/share/proj/proj.db", {st_mode=S_IFREG|0644, st_size=8925184, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=8925184, ...}) = 0
stat("/usr/share/proj/proj.db", {st_mode=S_IFREG|0644, st_size=8925184, ...}) = 0
close(3)                                = 0
writev(2, [{iov_base="free(): invalid pointer", iov_len=23}, {iov_base="\n", iov_len=1}], 2free(): invalid pointer
) = 24
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f2914b82000
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 49281
gettid()                                = 49281
tgkill(49281, 49281, SIGABRT)           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=49281, si_uid=1001} ---

+++ killed by SIGABRT (core dumped) +++
```

I am writing this here because it seems to come from proj.db ???
There is no problem with proj-data-6.3.1 with proj.db from 2020

and this leads to more problem afterwards when trying to run terracotta optimize-rasters

```
$ terracotta optimize-rasters ../NaturalnessBZHv1.tif -o optimized/
proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
Optimizing 1 file on 1 process
NaturalnessBZHv1.tif ... (1/1)
proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
free(): invalid pointer
Aborted (core dumped)
```

Any idea/help on how to fix this ?

I have no prolbem on archlinux, with proj 8.0.0 and python 3.9.9

**Comment by solsticedhiver** [comment]
After having upgrade *rasterio*, it works for `optimze-rasters` or `ingest` but not for `server`

It enforces the version 1.1.8
```

$ terracotta serve -d cartnat.sqlite 
 [-] Uncaught exception!
Traceback (most recent call last):
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rasterio 1.2.10 (/home/terracotta4mopga/tc4m/lib/python3.9/site-packages), Requirement.parse('rasterio<=1.1.8,>=1.0'), {'terracotta'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/terracotta/scripts/cli.py", line 52, in entrypoint
    cli(obj={})
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/terracotta/scripts/serve.py", line 57, in serve
    from terracotta.server import create_app
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/terracotta/server/__init__.py", line 6, in <module>
    from terracotta.server.flask_api import create_app  # noqa: F401
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/terracotta/server/flask_api.py", line 6, in <module>
    from apispec_webframeworks.flask import FlaskPlugin
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/apispec_webframeworks/__init__.py", line 1, in <module>
    import pkg_resources
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/terracotta4mopga/tc4m/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rasterio<=1.1.8,>=1.0' distribution was not found and is required by terracotta
```

**Comment by dionhaefner** [comment]
I agree, it's time to unpin rasterio. Performance is slightly worse but it's not as bad as it was.

**Comment by dionhaefner** [comment]
Done.
