### ISSUE TITLE
Windows 10 Installation

### ISSUE THREAD

**Issue by zufryy** [DHI-GRAS/terracotta#272]
Hi All,

I am trying to install terracotta on the Windows 10 by following the steps in here : https://terracotta-python.readthedocs.io/en/latest/tutorials/windows.html

I am using Miniconda3 Windows 64-bit with python v3.8

I got this error when running this command "conda env create -f environment.yml"

`Pip subprocess output:
Obtaining file:///D:/Wadugs-Alpha/Webmap/terracotta (from -r D:\Wadugs-Alpha\Webmap\terracotta\condaenv.w2irkg_2.requirements.txt (line 1))
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\Wadugs-Alpha\Webmap\terracotta\setup.py", line 20, in <module>
          setup(
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\dist.py", line 476, in __init__
          _Distribution.__init__(
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\_distutils\dist.py", line 280, in __init__
          self.finalize_options()
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\dist.py", line 900, in finalize_options
          ep(self)
        File "C:\Users\zufry\miniconda3\envs\terracotta\lib\site-packages\setuptools\dist.py", line 920, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "d:\wadugs-alpha\webmap\terracotta\.eggs\setuptools_scm-7.0.5-py3.10.egg\setuptools_scm\integration.py", line 90, in version_keyword
          _assign_version(dist, config)
        File "d:\wadugs-alpha\webmap\terracotta\.eggs\setuptools_scm-7.0.5-py3.10.egg\setuptools_scm\integration.py", line 59, in _assign_version
          maybe_version = _get_version(config)
        File "d:\wadugs-alpha\webmap\terracotta\.eggs\setuptools_scm-7.0.5-py3.10.egg\setuptools_scm\__init__.py", line 163, in _get_version
          dump_version(
        File "d:\wadugs-alpha\webmap\terracotta\.eggs\setuptools_scm-7.0.5-py3.10.egg\setuptools_scm\__init__.py", line 78, in dump_version
          with open(target, "w") as fp:
      FileNotFoundError: [Errno 2] No such file or directory: 'terracotta\\_version.py'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed`

Are there any extra steps to overcome this error message?
Thank you in advance

**Comment by dionhaefner** [comment]
Unfortunately I can't reproduce (on OSX). Is this Terracotta master or did you download a release?

**Comment by zufryy** [comment]
I am using this command (git clone https://github.com/DHI-GRAS/terracotta.git) to download the files

**Comment by dionhaefner** [comment]
Could any Windows users try this? @panakouris

**Comment by panakouris** [comment]
I couldn't reproduce this using Miniconda3 Windows 64-bit with python v3.8. The environment was created successfully in my case

**Comment by dionhaefner** [comment]
Thanks for testing. @zufryy could you please write down exactly which commands you are using?

**Comment by zufryy** [comment]
Thanks for the quick reply.  I am using Windows 10 Home Edition (not sure if it will give a difference or not).
 I am following the same commands that are written here https://terracotta-python.readthedocs.io/en/latest/tutorials/windows.html

In addition to that, I am trying to use another machine that running on Windows 8.1 Single Language Edition, but it give me the same error.

**Comment by dionhaefner** [comment]
[Works on CI, too](https://github.com/DHI-GRAS/terracotta/runs/7858322911?check_suite_focus=true).

Could you confirm that this is essentially what you are running?

```bash
$ git clone https://github.com/DHI-GRAS/terracotta.git
$ cd terracotta
$ conda env create -f environment.yml
```

Could you show the output of `ls` or `dir` from the `terracotta` folder?

**Comment by zufryy** [comment]
So the command prompt that I used is "Anaconda Powershell Prompt (miniconda3)" to run the code that command that you mentioned.

```
(base) PS D:\Wadugs-Alpha\Webmap\terracotta> ls


    Directory: D:\Wadugs-Alpha\Webmap\terracotta


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/16/2022   2:17 PM                .github
d-----         8/16/2022   2:17 PM                docs
d-----         8/16/2022   2:17 PM                tests
-a----         8/16/2022   2:17 PM            213 .coveragerc
-a----         8/16/2022   2:17 PM           1233 .gitattributes
-a----         8/16/2022   2:17 PM           1514 .gitignore
-a----         8/16/2022   2:17 PM            184 .pre-commit-config.yaml
-a----         8/16/2022   2:17 PM            181 environment.yml
-a----         8/16/2022   2:17 PM           1065 LICENSE
-a----         8/16/2022   2:17 PM           5271 README.md
-a----         8/16/2022   2:17 PM            211 readthedocs.yml
-a----         8/16/2022   2:17 PM            980 setup.cfg
-a----         8/16/2022   2:17 PM           3440 setup.py
-a----         8/16/2022   2:17 PM            143 zappa_requirements.txt
-a----         8/16/2022   2:17 PM           1059 zappa_settings.toml.in
-a----         8/16/2022   2:17 PM           1514 zappa_settings_callback.py
```

**Comment by zufryy** [comment]
Oh gosh, I feel really stupid.  It is working fine when I put back the terracotta folder.  I am so sorry for this mistake.  Thank you very much for your support.
