### ISSUE TITLE
different table schema in sqlite driver between conda and pip terracotta version 

### ISSUE THREAD

**Issue by ciskoh** [DHI-GRAS/terracotta#286]
Hi all,
I am trying to deploy terracotta to AWS but having issues. While trying to debug I realised that there is a discrepancy between the conda version and the pip version of  terracotta, despite both being 0.7.5.

in the sqlite database installed with pip the keys table is called keys, while in the conda version the table is called key_names with the primary key also called "key_name" instead of "key". This obviously creates problems when trying to run the db  with `terracotta serve -d`

**Comment by dionhaefner** [comment]
How did you install Terracotta via conda?

**Comment by ciskoh** [comment]
https://anaconda.org/conda-forge/terracotta

**Comment by dionhaefner** [comment]
Who maintains that conda-forge feedstock? I didn't even know we had that.

**Comment by j08lue** [comment]
> I ingested the geotiffs in the environment with python 3.10 (MAC os X-conda) and then I tried to serve them from the environment with python 3.8 (linux-pip)

I think the difference is ingest/serve then rather than conda/pip. We may have heuristics for one to guess at the DB driver, but not the other. 🤷

https://github.com/DHI-GRAS/terracotta/blob/964a72b022bea565a10a73d6cce0a40542304a90/terracotta/scripts/serve.py#L29-L30

**Comment by ciskoh** [comment]
so if I specify the driver "sqlite" I should be able to use the new database schema with only the "keys" instead of "key_names"?
obviously once I deploy I need to use sqlite-remote, should I use sqlite-remote also while ingesting?

**Comment by j08lue** [comment]
Would it work for you to use the newest version from GitHub instead? Any confusion with table names should be gone there.

`pip install git+https://github.com/DHI-GRAS/terracotta.git`

When you deploy with Zappa, it zips the virtual environment you are deploying from, so whatever version is installed there will get shipped - you are not required to use a version that is on PyPI.

Otherwise - yes, specifying the driver both during ingest and when serving should help.

**Comment by ciskoh** [comment]
@j08lue solution didn't work for me. A this point I will explain you what I tried, maybe I am doing something wrong.

env1 (Mac OS X python 10). Installed terracotta via pip. Ingested files using python api (specifying provider=sqlite). I get a sqlite db with keys table (not key_names). Tested and it works like a charm, but if I try deploying with Zappa I get the error: AWS does not support python 3.10 ....

Env 2. (Mac OS X pthon3.9) clone the code from github install all requirements via pip
`pip install -r zappa_requirements.txt` & `pip install -e .` If I try `terracotta serve -d /path/to/db.sqlite` and then `terracotta connect localhost:5001`  I get aborted and the following error:

``` [-] Exception on /keys [GET]
Traceback (most recent call last):
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/relational_meta_store.py", line 49, in convert_exceptions
    yield
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/relational_meta_store.py", line 276, in get_keys
    keys_table = sqla.Table('key_names', self.sqla_metadata, autoload_with=self.sqla_engine)
  File "<string>", line 2, in __new__
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 619, in __new__
    metadata._remove_table(name, schema)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 614, in __new__
    table._init(name, metadata, *args, **kw)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 689, in _init
    self._autoload(
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/sql/schema.py", line 724, in _autoload
    conn_insp.reflect_table(
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 789, in reflect_table
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: key_names

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/server/keys.py", line 38, in get_keys
    payload = {'keys': keys()}
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/handlers/keys.py", line 19, in keys
    for key, description in driver.get_keys().items():
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/base_classes.py", line 43, in inner
    return fun(self, *args, **kwargs)
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/terracotta_driver.py", line 112, in get_keys
    return self.meta_store.get_keys()
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/base_classes.py", line 43, in inner
    return fun(self, *args, **kwargs)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/anaconda3/envs/mapserver/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/matteojuckerriva/Desktop/code/MapServer/terracotta/terracotta/drivers/relational_meta_store.py", line 51, in convert_exceptions
    raise exceptions.InvalidDatabaseError(error_message) from exception
terracotta.exceptions.InvalidDatabaseError: Could not retrieve keys from database
127.0.0.1 - - [22/Dec/2022 16:46:27] "GET /keys HTTP/1.1" 500 -````
For clarity I get the same error even if I specify `--database-provider sqlite `or `--database-provider sqlite-remote`

If I manually modify the schema of the db changing the tables keys to key names and a few column names I can do `serve` and `connect` and everything works. But when I try to deploy zappa fails with an error: 
`aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open``

env3. (Linux python 3.8). Same procedure as for env2. The `serve` works only for database2 (manually modified version) , `zappa deploy development` works but if I try `terracotta connect https://my_lambda_address/development ` I can see no image being served. Note that both the sqlite database and the images are on an S3 bucket with public access activated

**Comment by ciskoh** [comment]
This is the list of table and column names I had to change:

```
Table keys:
- Table "keys" -> "key_names"
- Column "names" -> "key_names"

Table datasets:
- Column "filepath" -> "path"
```
and this is my zappa_settings

```
[development]
app_function = "terracotta.server.app.app"
aws_region = "eu-central-1"
profile_name = "default"
project_name = "tc-mapserver"
runtime = "python3.9"
s3_bucket = "flood-protect-storage"
exclude = [
    "*.gz",
    "*.rar",
    "boto3*",
    "botocore*",
    "s3transfer*",
    "awscli*",
    ".mypy_cache",
    ".pytest_cache",
    ".eggs"
]
debug = true
log_level = "DEBUG"
xray_tracing = true
touch_path = "/keys"

timeout_seconds = 30
memory_size = 500

    [development.aws_environment_variables]
    TC_DRIVER_PATH = "s3://flood-protect-storage/db2.sqlite"
    TC_DRIVER_PROVIDER = "sqlite-remote"
    TC_REPROJECTION_METHOD = "linear"
    TC_RESAMPLING_METHOD = "average"
    TC_XRAY_PROFILE = "true"

    [development.callbacks]
    settings = "zappa_settings_callback.check_integrity"


[production]
extends = "development"

# WARNING: using a cache cluster incurs additional costs (not covered by AWS free tier)
cache_cluster_enabled = true
cache_cluster_size = 0.5
cache_cluster_ttl = 3600

debug = false
log_level = "WARNING"
xray_tracing = true
```

**Comment by dionhaefner** [comment]
It sounds like you are cloning & installing the master branch of terracotta, which is indeed incompatible with the latest release. Please check out a release tag instead.

**Comment by dionhaefner** [comment]
> But when I try to deploy zappa fails with an error:
aws_xray_sdk.core.exceptions.exceptions.SegmentNotFoundException: cannot find the current segment/subsegment, please make sure you have a segment open

This sounds like an issue with xray tracing on OSX (unrelated). Try disabling xray tracing and it should go away. If so we should investigate this in a separate issue.

**Comment by dionhaefner** [comment]
> zappa deploy development works but if I try terracotta connect https://my_lambda_address/development I can see no image being served. Note that both the sqlite database and the images are on an S3 bucket with public access activated

This can have many reasons; missing permissions is a popular one, but could also be broken paths. Please check the logs on AWS to find the actual exceptions thrown by the Lambda handlers.

**Comment by ciskoh** [comment]
Thnak you very much, will try disabling ray tracing and will try re-downloading the  terracotta branch.

> It sounds like you are cloning & pip-installing the master branch of terracotta, which is indeed incompatible with the latest release. Please check out a release tag instead.

May ask what you mean exactly? Should I get branch v0.7.5 instead of main?

**Comment by dionhaefner** [comment]
Yes, just use:

```bash
$ git clone git@github.com:DHI-GRAS/terracotta.git -b v0.7.5
```

Or, if you have already cloned the repository:

```bash
$ git checkout v0.7.5
```

**Comment by dionhaefner** [comment]
Did it work @ciskoh ?
