### ISSUE TITLE
rasterio error whey deploying to AWS lambda with zappa

### ISSUE THREAD

**Issue by agelosnm** [DHI-GRAS/terracotta#292]
I'm trying to deploy terracotta to AWS lambda following all the relevant instructions with the vritualenv etc [(A serverless Terracotta deployment on AWS Lambda)](https://terracotta-python.readthedocs.io/en/latest/tutorials/aws.html) using RDS as well and the below error comes up on "zappa deploy"

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "rasterio/crs.pyx", line 775, in rasterio.crs.CRS.from_user_input
  File "rasterio/_err.pyx", line 209, in rasterio._err.exc_wrap_ogrerr
rasterio._err.CPLE_BaseError: OGR Error code 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scio/anaconda3/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/scio/anaconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scio/devops/repos/terracotta/terracotta/raster.py", line 316, in get_raster_tile
    dst_bounds = warp.transform_bounds(src.crs, target_crs, *src.bounds)
  File "/home/scio/envs/tc-lambda/lib/python3.9/site-packages/rasterio/warp.py", line 148, in transform_bounds
    dst_crs = CRS.from_user_input(dst_crs)
  File "rasterio/crs.pyx", line 777, in rasterio.crs.CRS.from_user_input
rasterio.errors.CRSError: The WKT could not be parsed. OGR Error code 6
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scio/envs/tc-lambda/lib/python3.9/site-packages/zappa/cli.py", line 3044, in handle
    sys.exit(cli.handle())
  File "/home/scio/envs/tc-lambda/lib/python3.9/site-packages/zappa/cli.py", line 519, in handle
    self.dispatch_command(self.command, stage)
  File "/home/scio/envs/tc-lambda/lib/python3.9/site-packages/zappa/cli.py", line 557, in dispatch_command
    self.callback("settings")
  File "/home/scio/envs/tc-lambda/lib/python3.9/site-packages/zappa/cli.py", line 2171, in callback
    cb_func(self)  # Call the function passing self
  File "/home/scio/devops/repos/terracotta/zappa_settings_callback.py", line 45, in check_integrity
    driver.get_raster_tile(some_dataset)
  File "/home/scio/devops/repos/terracotta/terracotta/drivers/terracotta_driver.py", line 263, in get_raster_tile
    return self.raster_store.get_raster_tile(
  File "/home/scio/devops/repos/terracotta/terracotta/drivers/geotiff_raster_store.py", line 162, in get_raster_tile
    result = future.result()
  File "/home/scio/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/scio/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
rasterio.errors.CRSError: The WKT could not be parsed. OGR Error code 6

**Comment by dionhaefner** [comment]
Huh, haven't seen that one before. Can you give us a bit more information about your setup? What OS, how did you install rasterio / GDAL?

**Comment by agelosnm** [comment]
I haven't install GDAL. I just run the "pip install" commands without any issues

**Comment by dionhaefner** [comment]
Could you try running this command and see if you get the same error?

```bash
$ python -c "from rasterio.crs import CRS; print(CRS.from_user_input('epsg:3857'))"
```

**Comment by agelosnm** [comment]
Thanks for your comment!

Yes, the same error appears when running this command

**Comment by dionhaefner** [comment]
Okay. So your installation is broken, but I'm not exactly sure *how* it's broken. I suggest you re-install everything, and if that doesn't work, open an issue at [rasterio](https://github.com/rasterio/rasterio).
