### ISSUE TITLE
Error on get_datasets with Postgresql database

### ISSUE THREAD

**Issue by bartwalczak** [DHI-GRAS/terracotta#295]
I'm installing terracotta inside a docker image via pip `pip install git+https://github.com/DHI-GRAS/terracotta.git`

After I ingest a folder of files into a postgresql database using:
```
tcd.insert(key.dict(), cog)
```
(Where `key.dict()` returns valid `Mapping[str, str]`)

I run into an exception trying to obtain datasets:

```
existing_sets = tcd.get_datasets()
```

```
Traceback (most recent call last):
  File "/scripts/./ingest.py", line 135, in <module>
    ingest()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/scripts/./ingest.py", line 109, in folder
    existing_sets = tcd.get_datasets()
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/base_classes.py", line 43, in inner
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/terracotta_driver.py", line 131, in get_datasets
    return self.meta_store.get_datasets(
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/base_classes.py", line 43, in inner
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/relational_meta_store.py", line 329, in get_datasets
    datasets = {keytuple(row): row['path'] for row in result}
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/relational_meta_store.py", line 329, in <dictcomp>
    datasets = {keytuple(row): row['path'] for row in result}
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/relational_meta_store.py", line 327, in keytuple
    return tuple(row[key] for key in self.key_names)
  File "/usr/local/lib/python3.10/site-packages/terracotta/drivers/relational_meta_store.py", line 327, in <genexpr>
    return tuple(row[key] for key in self.key_names)
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 67, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
```

I could swear that it was working a month ago, but I'm not seeing any commits to main that would change anything. I must be missing something obvious again.

**Comment by j08lue** [comment]
So the traceback says that `row` in 329 is a tuple, not a str str mapping. https://github.com/DHI-GRAS/terracotta/blob/964a72b022bea565a10a73d6cce0a40542304a90/terracotta/drivers/relational_meta_store.py#L324-L329

`row` is an [`sqlalchemy.cyextension.resultproxy.BaseRow`](https://github.com/sqlalchemy/sqlalchemy/blob/b99b0c522ddb94468da27867ddfa1f7e2633c920/lib/sqlalchemy/cyextension/resultproxy.pyx#L10) and its `__getitem__` indeed indexes a tuple. 🤷 

Not sure why we are getting this now. Looks like an internal bug, though, maybe arising from changes in SQLAlchemy. Do the tests still pass? Will check that later..

**Comment by dionhaefner** [comment]
Tests were broken, the cause is that SQLalchemy 2.0 dropped the (deprecated) dict-like interface to rows.
